-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 16:12:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema referencias_g84
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema referencias_g84
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `referencias_g84` DEFAULT CHARACTER SET utf8 ;
USE `referencias_g84` ;

-- -----------------------------------------------------
-- Table `referencias_g84`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`tipo_documento` (
  `tipdoc_id` INT NOT NULL AUTO_INCREMENT,
  `tipdoc_nombre` VARCHAR(50) NOT NULL,
  `tipdoc_abrevitura` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`tipdoc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`genero` (
  `gen_id` INT NOT NULL AUTO_INCREMENT,
  `gen_nombre` VARCHAR(50) NOT NULL,
  `gen_abrevitura` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`gen_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`estado_civil` (
  `estciv_id` INT NOT NULL AUTO_INCREMENT,
  `estciv_nombre` VARCHAR(50) NOT NULL,
  `estciv_abreviatura` VARCHAR(10) NULL,
  PRIMARY KEY (`estciv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`tipo_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`tipo_referencia` (
  `tipref_id` INT NOT NULL AUTO_INCREMENT,
  `tipref_nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tipref_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`empresa` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `emp_nombre` VARCHAR(100) NOT NULL,
  `emp_nit` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`empleado` (
  `emplea_id` INT NOT NULL AUTO_INCREMENT,
  `emplea_pimer_nombre` VARCHAR(50) NOT NULL,
  `emplea_segundo_nombre` VARCHAR(50) NULL,
  `emplea_pimer_apellido` VARCHAR(50) NOT NULL,
  `emplea_segundo_apellido` VARCHAR(50) NULL,
  `emplea_tipo_documento` INT NOT NULL,
  `emplea_genero` INT NOT NULL,
  `emplea_estado_civil` INT NOT NULL,
  `emplea_fecha_nacimiento` DATE NOT NULL,
  `emplea_direccion` VARCHAR(100) NOT NULL,
  `empresa_empresa` INT NOT NULL,
  PRIMARY KEY (`emplea_id`),
  INDEX `empleado_FK_tipo_documento_idx` (`emplea_tipo_documento` ASC) ,
  INDEX `empleado_FK_genero_idx` (`emplea_genero` ASC) ,
  INDEX `empleado_FK_estado_civil_idx` (`emplea_estado_civil` ASC) ,
  INDEX `fk_empleado_empresa1_idx` (`empresa_empresa` ASC) ,
  CONSTRAINT `empleado_FK_tipo_documento`
    FOREIGN KEY (`emplea_tipo_documento`)
    REFERENCES `referencias_g84`.`tipo_documento` (`tipdoc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado_FK_genero`
    FOREIGN KEY (`emplea_genero`)
    REFERENCES `referencias_g84`.`genero` (`gen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado_FK_estado_civil`
    FOREIGN KEY (`emplea_estado_civil`)
    REFERENCES `referencias_g84`.`estado_civil` (`estciv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_empresa1`
    FOREIGN KEY (`empresa_empresa`)
    REFERENCES `referencias_g84`.`empresa` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`ciudad` (
  `ciu_id` INT NOT NULL AUTO_INCREMENT,
  `ciu_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ciu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`referencia` (
  `ref_id` INT NOT NULL AUTO_INCREMENT,
  `ref_nombre` VARCHAR(100) NOT NULL,
  `ref_direccion` VARCHAR(100) NULL,
  `ref_mail` VARCHAR(100) NOT NULL,
  `ref_telefono` VARCHAR(50) NULL,
  `ref_celular` VARCHAR(50) NOT NULL,
  `ref_ciudad` INT NOT NULL,
  PRIMARY KEY (`ref_id`),
  INDEX `referencia_FK_ciudad_idx` (`ref_ciudad` ASC) ,
  CONSTRAINT `referencia_FK_ciudad`
    FOREIGN KEY (`ref_ciudad`)
    REFERENCES `referencias_g84`.`ciudad` (`ciu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `referencias_g84`.`empleado_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `referencias_g84`.`empleado_referencia` (
  `empref_empleado` INT NOT NULL,
  `empref_referencia` INT NOT NULL,
  `empref_tipo_referencia` INT NOT NULL,
  PRIMARY KEY (`empref_empleado`, `empref_referencia`),
  INDEX `empleado_referencia_FK_referencia_idx` (`empref_referencia` ASC) ,
  INDEX `empleado_referencia_idx` (`empref_tipo_referencia` ASC) ,
  CONSTRAINT `empleado_referencia_FK_empleado`
    FOREIGN KEY (`empref_empleado`)
    REFERENCES `referencias_g84`.`empleado` (`emplea_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado_referencia_FK_referencia`
    FOREIGN KEY (`empref_referencia`)
    REFERENCES `referencias_g84`.`referencia` (`ref_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado_referencia`
    FOREIGN KEY (`empref_tipo_referencia`)
    REFERENCES `referencias_g84`.`tipo_referencia` (`tipref_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
